### ISSUE TITLE
Memory allocation on TryFirst<T>()

### ISSUE THREAD

**Issue by rogetsss** [outerminds/Entia#14]
It seems that calling TryFirst<T>() on a group will cause an allocation of 48B every time it's called.

![image](https://user-images.githubusercontent.com/13680836/56395710-b0167400-6209-11e9-9805-3c2ab2a669a6.png)

Example:
`if (GroupInputs.TryFirst(out Write<Components.CharacterInput> inputItem))`

**Comment by Magicolo** [comment]
This was a boxing issue. The `GetEnumerator` call in the `TryFirst` extension would box the struct enumerator. I have resolved this issue by adding a `IEnumerable<TEnumerator, TItem>` interface which removes all allocations for operations that don't require allocations such as `TryFirst`.

As a bonus, the previously required item type `out Write<Components.CharacterInput> inputItem` (required for generic type resolution) doesn't need to be specified anymore. A simple `out var inputItem` will work as it should.

Note that the `Entia.Core` namespace must be in use for the compiler to resolve to the appropriate extension.

This fix will be available in the next Entia release.
